[package]
name = "bangbang_six"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"
local-ip-address = "0.6.1"
raylib = "3.7.0"
